# validate-configs.yml
name: Validate Configurations

on:
  push:
    paths:
      - 'dns/config/**'
      - 'dhcp/config/**'
  pull_request:
    paths:
      - 'dns/config/**'
      - 'dhcp/config/**'

jobs:
  validate-dns:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install BIND tools
        run: |
          sudo apt-get update
          sudo apt-get install -y bind9utils bind9

      - name: Create required directories
        run: |
          sudo mkdir -p /var/named/dynamic
          sudo mkdir -p /var/named/data
          sudo chown -R root:root /var/named

      - name: Validate named.conf
        run: |
          sudo named-checkconf dns/config/named.conf

      - name: Validate zone files
        run: |
          cd dns/config
          sudo named-checkzone lab.com db.lab.com
          sudo named-checkzone 10.168.192.in-addr.arpa db.10.168.192

      - name: Check for required DNS records
        run: |
          cd dns/config
          for domain in partner engg clust kvm cicd; do
            if ! grep -q "api.$domain" db.lab.com; then
              echo "Missing api.$domain record"
              exit 1
            fi
            if ! grep -q "*.apps.$domain" db.lab.com; then
              echo "Missing *.apps.$domain record"
              exit 1
            fi
          done

  validate-dhcp:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install ISC DHCP server
        run: |
          sudo apt-get update
          sudo apt-get install -y isc-dhcp-server

      - name: Create required directories
        run: |
          sudo mkdir -p /etc/dhcp
          sudo cp dhcp/config/dhcpd.conf /etc/dhcp/
          sudo chown -R root:root /etc/dhcp

      - name: Validate dhcpd.conf
        run: |
          cd dhcp/config
          sudo dhcpd -t -cf dhcpd.conf || true
          # Note: dhcpd might return non-zero even with valid config due to missing interfaces

      - name: Check for required DHCP configuration
        run: |
          cd dhcp/config
          if ! grep -q "subnet 192.168.10.0 netmask" dhcpd.conf; then
            echo "Missing subnet configuration for 192.168.10"
            exit 1
          fi

  validate-file-structure:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Check required files exist
        run: |
          required_files=(
            "dns/config/named.conf"
            "dns/config/db.lab.com"
            "dns/config/db.10.168.192"
            "dns/src/Dockerfile"
            "dhcp/src/Dockerfile"
            "deploy.sh"
          )

          for file in "${required_files[@]}"; do
            if [ ! -f "$file" ]; then
              echo "Missing required file: $file"
              exit 1
            fi
          done

      - name: Check directory structure
        run: |
          required_dirs=(
            "dns/config"
            "dns/data"
            "dns/src"
            "dhcp/config"
            "dhcp/data"
            "dhcp/src"
            "nfs/config"
            "nfs/data"
          )

          for dir in "${required_dirs[@]}"; do
            if [ ! -d "$dir" ]; then
              mkdir -p "$dir"
            fi
          done

  validate-syntax:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Check syntax of configuration files
        run: |
          cd dns/config
          for file in *.zone db.*; do
            if [ -f "$file" ]; then
              if grep -q '[^[:space:]]$' "$file"; then
                echo "Warning: $file contains lines ending without whitespace"
              fi
              if ! grep -q "IN.*SOA" "$file"; then
                echo "Error: $file missing SOA record"
                exit 1
              fi
            fi
          done
