name: Validate Documentation

on:
  push:
    paths:
      - '**.org'
  pull_request:
    paths:
      - '**.org'

jobs:
  validate-org:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Install Emacs
        run: |
          sudo apt-get update
          sudo apt-get install -y emacs

      - name: Validate Org syntax
        run: |
          emacs --batch --eval "(require 'org)" --eval "(org-lint-file \"README.org\")"

  validate-documentation:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Check required documentation
        run: |
          if [ ! -f "README.org" ]; then
            echo "README.org is missing"
            exit 1
          fi
