---
name: Validate Documentation

on:
  push:
    paths:
      - '**.org'
  pull_request:
    paths:
      - '**.org'

jobs:
  validate-org:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install Emacs
        run: |
          sudo apt-get update
          sudo apt-get install -y emacs-nox

      - name: Validate Org syntax
        run: |
          # Create minimal init file to load org-mode
          echo "(require 'org)" > init.el
          echo "(require 'org-lint)" >> init.el
          emacs --batch --no-init-file --load init.el --eval '(org-lint-file "README.org")'

  validate-documentation:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Check required documentation
        run: |
          if [ ! -f "README.org" ]; then
            echo "README.org is missing"
            exit 1
          fi
